site_name: yonesty Dokumentation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/yonesty.css

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
nav:
  - Startseite: index.md

  - Erste Schritte:
      - Kernmerkmale von yonesty: Kernmerkmale-von-yonesty-verstehen.md
      - Typische Startpfade: Getting-Started-Typische-Startpfade.md
      - Rollen und Use Cases verstehen: Starte-mit-deiner-Rolle-und-typischen-Use-Cases.md
      - Demo Unternehmen Hammer & Nagel GmbH: demo-hammer-und-nagel-gmbh.md
      - Rollenüberblick: Überblick-Welche-Rolle-übernimmt-welche-Aufgaben.md

  - Basics:
      - Wichtige Begriffe: Wichtige-Begriffe.md
      - Organisation: Themenbereich Organisation.md
      - Personen und Teams: Themenbereich Personen und Teams.md
      - Berechtigungen: Themenbereich Berechtigungen.md
      - News: Themenbereich News.md
      - Rollen: Themenbereich-Rollen.md
      - Prozesse: Themenbereich-Prozesse.md
      - Ziele: Themenbereich-Ziele.md
      - Feedback: Themenbereich-Feedback.md
      - Fähigkeiten, Erwartungen und Gefühle: Themenbereich-Fähigkeiten-Erwartungen-und-Gefuehle.md
      - Aktivitäten: Aktivitäten-Your-Next-Steps.md
  
  - Leistung:
      - RACI und Matrizen: RACI-und-Matrizen.md
      - Suche, Filtern, Teilen, Export: Suche-Filtern-Teilen-Export.md

  - Begeisterung mit KI:
      - Yona KI Assistent: Yona.md
  


copyright: >
  © 2026 yonesty powered by soletti
extra:
  generator: false
