site_name: yonesty Dokumentation

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/yonesty.css

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  
nav:
  - Startseite: index.md

  - Erste Schritte:
      - Kernmerkmale von yonesty: Kernmerkmale-von-yonesty-verstehen.md
      - Typische Startpfade: Getting-Started-Typische-Startpfade.md
      - Rollen und Use Cases verstehen: Starte-mit-deiner-Rolle-und-typischen-Use-Cases.md
      - Demo Unternehmen Hammer & Nagel GmbH: demo-hammer-und-nagel-gmbh.md
      - Rollenüberblick: Überblick-Welche-Rolle-übernimmt-welche-Aufgaben.md

  - Basis-Merkmale:
      - Wichtige Begriffe: Wichtige-Begriffe.md
      - Organisation: Organisation.md
      - Personen und Teams: Personen-und-Teams.md
      - Berechtigungen: Berechtigungen.md
      - News: News.md
      - Rollen: Rollen.md
      - Prozesse: Prozesse.md
      - Ziele: Ziele.md
      - Feedback: Feedbacks.md
      - Fähigkeiten, Erwartungen und Gefühle: Faehigkeiten-Erwartungen-und-Gefuehle.md
      - Aktivitäten: Aktivitäten-Your-Next-Steps.md
      - Suche, Filtern, Teilen, Export: Suche-Filtern-Teilen-Export.md
  
  - Leistungsmerkmale:
      - Rollen mit Prozessen verbinden: Leistungsmerkmal-Rollen-mit-Prozessen-verbinden.md
      - Prozesse mit Zielen verbinden: Leistungsmerkmal-Prozesse-mit-Zielen-verbinden.md
      - Ziele mit Verantwortlichen verbinden: Leistungsmerkmal-Ziele-mit-Verantwortlichen-verbinden.md
      - Fähigkeiten mit Rollen verbinden: Leistungsmerkmal-Faehigkeiten-mit-Rollen-verbinden.md
      - Feedback mit Rollen, Zielen und Fähigkeiten verbinden: Leistungsmerkmal-Feedback-mit-Rollen-Zielen-und-Faehigkeiten-verbinden.md
      - Aus Feedback Aktivitäten ableiten: Leistungsmerkmal-Aus-Feedback-Aktivitaeten-ableiten.md
      - Aktivitäten mit Zielen und Entwicklung verbinden: Leistungsmerkmal-Aktivitaeten-mit-Zielen-und-Entwicklung-verbinden.md
      - RACI und Matrizen nutzen: RACI-und-Matrizen.md      

  - Begeisterung mit KI:
      - Yona KI Assistent: Yona.md

  - Administration:
      - Microsoft Azure Synchronisation Personen: Administration.md

copyright: >
  © 2026 yonesty powered by soletti
extra:
  generator: false
